# Generated by Django 5.1.5 on 2025-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulatorio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('adulti', 'Per adulti'), ('pediatrico', 'Pediatrico'), ('prelievi', 'Sala prelievi'), ('medicazioni', 'Sala medicazioni')], max_length=20)),
            ],
        ),
    ]
