# Generated by Django 5.1.5 on 2025-06-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulatorio',
            name='tipo',
            field=models.CharField(choices=[('visite', 'Ambulatorio Visite'), ('prestazioni', 'Ambulatorio Prestazioni')], max_length=20),
        ),
        migrations.CreateModel(
            name='AmbulatorioPrestazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotto_tipo', models.CharField(choices=[('prelievi', 'Sala prelievi'), ('medicazioni', 'Sala medicazioni')], max_length=20)),
                ('ambulatorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ambulatorio.ambulatorio')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulatorioVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotto_tipo', models.CharField(choices=[('adulti', 'Per adulti'), ('pediatrico', 'Pediatrico')], max_length=20)),
                ('ambulatorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ambulatorio.ambulatorio')),
            ],
        ),
    ]
