@startuml

left to right direction
actor Infermiere as Nurse

rectangle CasaSalute {
	
	usecase "Visualizzazione delle prestazioni da eseguire" as UC_viewprestazioni
	usecase "Inserire esito delle prestazioni" as UC_compilaprestazioni
    usecase "Autenticazione" as UC_Authentication
}

Nurse --> UC_Authentication
Nurse --> UC_viewprestazioni
Nurse --> UC_compilaprestazioni
@enduml

