# Generated by Django 5.1.5 on 2025-01-27 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulatorio', models.CharField(max_length=255)),
                ('esito', models.TextField()),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('urgenza', models.BooleanField(default=False)),
                ('tipo_visita', models.CharField(choices=[('curante', 'Medico Curante'), ('sostituzione', 'In Sostituzione del Medico Curante'), ('urgenza', "D'Urgenza")], max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
        ),
    ]
