# Generated by Django 5.1.5 on 2025-01-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='ambulatorio',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='urgenza',
        ),
        migrations.AddField(
            model_name='visita',
            name='regime',
            field=models.CharField(choices=[('ordinaria', 'Ordinaria'), ('urgente', 'Urgente')], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='esito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo_visita',
            field=models.CharField(choices=[('pediatrica', 'Pediatrica'), ('adulti', 'Per Adulti')], max_length=20),
        ),
    ]
