# Generated by Django 5.1.5 on 2025-01-30 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0002_remove_visita_ambulatorio_remove_visita_urgenza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visita',
            name='regime',
            field=models.CharField(choices=[('ordinaria', 'Ordinaria'), ('urgente', 'Urgente')], default='ordinaria', max_length=20),
        ),
    ]
