# Generated by Django 5.1.5 on 2025-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0003_alter_visita_data_alter_visita_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
