# Generated by Django 5.1.5 on 2025-01-30 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0004_alter_visita_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
