# Generated by Django 5.1.5 on 2025-01-30 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_medico_data_di_nascita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visita', models.CharField(choices=[('pediatrica', 'Pediatrica'), ('adulti', 'Per Adulti')], max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ora', models.TimeField()),
                ('regime', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('urgente', 'Urgente')], default='ordinaria', max_length=20)),
                ('esito', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Paziente')),
            ],
        ),
    ]
