# Generated by Django 5.1.5 on 2025-06-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulatorio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneVisita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('tipo', models.CharField(choices=[('adulti', 'Per adulti'), ('pediatrica', 'Pediatrica')], max_length=20)),
                ('regime', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('urgente', 'Urgente')], max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
            options={
                'verbose_name': 'Prenotazione visita',
                'verbose_name_plural': 'Prenotazioni visite',
                'ordering': ['data', 'ora'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('esito', models.TextField(blank=True, null=True)),
                ('ambulatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulatorio.ambulatorio')),
                ('prenotazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visita.prenotazionevisita')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visite',
            },
        ),
    ]
