# Generated by Django 5.1.5 on 2025-05-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_indirizzo_infermiere_giorni_servizio_and_more'),
        ('visita', '0002_alter_visita_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_visita', to='users.medico'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='paziente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_visita', to='users.paziente'),
        ),
    ]
