# Generated by Django 5.1.5 on 2025-06-17 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazionePrestazione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], max_length=20)),
                ('data', models.DateField()),
                ('orario', models.TimeField()),
            ],
            options={
                'verbose_name': 'prenotazione prestazione',
                'verbose_name_plural': 'prenotazioni prestazioni',
                'ordering': ['data', 'orario'],
            },
        ),
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('esito', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'prestazione',
                'verbose_name_plural': 'prestazioni',
                'ordering': ['data'],
            },
        ),
    ]
