# Generated by Django 5.1.5 on 2025-01-30 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_infermiere_data_di_nascita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestazione', models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], max_length=20)),
                ('data_prenotazione', models.DateField(default=django.utils.timezone.now)),
                ('ora_prenotazione', models.TimeField()),
                ('data_prestazione', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('esito', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('infermiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.infermiere')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
        ),
    ]
