# Generated by Django 5.1.5 on 2025-01-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestazione', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestazione',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='prestazione',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='prestazione',
            name='nome',
        ),
        migrations.AddField(
            model_name='prestazione',
            name='data_prenotazione',
            field=models.DateField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestazione',
            name='data_prestazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='esito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='infermiere',
            field=models.ForeignKey(default='defalut', on_delete=django.db.models.deletion.CASCADE, to='users.infermiere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestazione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='ora_prenotazione',
            field=models.TimeField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestazione',
            name='paziente',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='users.paziente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestazione',
            name='tipo_prestazione',
            field=models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], default='default', max_length=20),
            preserve_default=False,
        ),
    ]
