# Generated by Django 5.1.5 on 2025-06-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulatorio', '0001_initial'),
        ('prestazione', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazioneprestazione',
            name='paziente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente'),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='ambulatorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulatorio.ambulatorio'),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='infermiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_infermiere', to='users.infermiere'),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='paziente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazioni', to='users.paziente'),
        ),
        migrations.AddField(
            model_name='prestazione',
            name='prenotazione',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestazione.prenotazioneprestazione'),
        ),
    ]
