# Generated by Django 5.1.5 on 2025-01-30 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestazione', '0002_remove_prestazione_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestazione',
            name='data_prenotazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prestazione',
            name='data_prestazione',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
