# Generated by Django 5.1.5 on 2025-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestazione', '0003_alter_prestazione_data_prenotazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestazione',
            name='data_prenotazione',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='prestazione',
            name='data_prestazione',
            field=models.DateField(blank=True, default='2023-01-01', null=True),
        ),
    ]
