# Generated by Django 5.1.5 on 2025-06-01 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('adulti', 'Per adulti'), ('pediatrico', 'Pediatrico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Infermiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('giorni_servizio', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('specialita', models.CharField(blank=True, max_length=100, null=True)),
                ('assenze_pianificate', models.JSONField(blank=True, null=True)),
                ('medici_sostituibili', models.ManyToManyField(blank=True, to='users.medico')),
                ('pazienti_in_cura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_pazienti_in_cura', to='users.medico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('data_nascita', models.DateField()),
                ('luogo_nascita', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medico_curante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_pazienti_curante', to='users.medico')),
                ('referente_adulto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paziente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('orario', models.TimeField()),
                ('tipo', models.CharField(choices=[('medico_curante', 'Visita con medico curante'), ('sostituto', 'Visita con medico sostituto'), ('urgenza', 'Visita d’urgenza')], max_length=20)),
                ('stato', models.CharField(default='Prenotato', max_length=20)),
                ('ambulatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ambulatorio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
            options={
                'ordering': ['data', 'orario'],
            },
        ),
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], max_length=20)),
                ('data', models.DateTimeField()),
                ('esito', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('infermiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_infermiere', to='users.infermiere')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazioni', to='users.paziente')),
            ],
        ),
        migrations.CreateModel(
            name='Segreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('ruolo', models.CharField(default='Segreteria', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prenotazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.prenotazione')),
            ],
        ),
    ]
