# Generated by Django 5.1.5 on 2025-06-17 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infermiere',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('giorni_servizio', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'infermiere',
                'verbose_name_plural': 'infermieri',
            },
        ),
        migrations.CreateModel(
            name='Segreteria',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('ruolo', models.CharField(default='Segreteria', max_length=100)),
            ],
            options={
                'verbose_name': 'segreteria',
                'verbose_name_plural': 'segreterie',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('specialita', models.CharField(blank=True, max_length=100, null=True)),
                ('assenze_pianificate', models.JSONField(blank=True, null=True)),
                ('medici_sostituibili', models.ManyToManyField(blank=True, to='users.medico')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medici',
            },
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cognome', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('data_nascita', models.DateField()),
                ('luogo_nascita', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medico_curante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_pazienti_curante', to='users.medico')),
                ('referente_adulto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paziente')),
            ],
            options={
                'verbose_name': 'paziente',
                'verbose_name_plural': 'pazienti',
            },
        ),
    ]
