# Generated by Django 5.1.5 on 2025-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infermiere',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('data_di_nascita', models.DateField(blank=True, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reparto', models.CharField(blank=True, max_length=255, null=True)),
                ('giorni_sala_prelievi', models.CharField(blank=True, max_length=255, null=True)),
                ('giorni_sala_medicazioni', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('codice_sanitario', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('data_di_nascita', models.DateField(blank=True, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('specializzazione', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medici_sostituibili', models.ManyToManyField(blank=True, related_name='medici_sostituti', to='users.medico')),
                ('pazienti_convenzionati', models.ManyToManyField(blank=True, related_name='medici_convenzionati', to='users.paziente')),
            ],
        ),
    ]
