# Generated by Django 5.1.5 on 2025-06-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infermiere',
            options={'verbose_name': 'Infermiere', 'verbose_name_plural': 'Infermieri'},
        ),
    ]
