# Generated by Django 5.1.5 on 2025-01-30 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_segreteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='data_di_nascita',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
