# Generated by Django 5.1.5 on 2025-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_infermiere_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='referente_adulto',
            field=models.CharField(blank=True, help_text='Nome e cognome del referente adulto per i minori', max_length=100, null=True),
        ),
    ]
