# Generated by Django 5.1.5 on 2025-01-30 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_medico_data_di_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='infermiere',
            name='data_di_nascita',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='infermiere',
            name='giorni_sala_medicazioni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infermiere',
            name='giorni_sala_prelievi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
