# Generated by Django 5.1.5 on 2025-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_paziente_referente_adulto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='email',
            field=models.EmailField(blank=True, help_text=' Email del referente adulto per i minori', max_length=254, null=True),
        ),
    ]
