# Generated by Django 5.1.5 on 2025-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_paziente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='specializzazione',
            field=models.CharField(blank=True, choices=[('medicina_generale', 'Medicina Generale'), ('pediatria', 'Pediatria'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia')], max_length=30, null=True),
        ),
    ]
