# Generated by Django 5.1.5 on 2025-01-30 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_infermiere_data_di_nascita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infermiere',
            name='indirizzo',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='infermiere',
            name='reparto',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='segreteria',
            name='data_di_nascita',
            field=models.DateField(blank=True, default='1990-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='infermiere',
            name='data_di_nascita',
            field=models.DateField(blank=True, default='1990-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='infermiere',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medici_sostituibili',
            field=models.ManyToManyField(blank=True, related_name='medici_sostituti', to='users.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='pazienti_convenzionati',
            field=models.ManyToManyField(blank=True, related_name='medici_convenzionati', to='users.paziente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='data_di_nascita',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='segreteria',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
