# Generated by Django 5.1.5 on 2025-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_medico_specializzazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='email',
            field=models.EmailField(default='insericiEmail@example.com', max_length=254),
        ),
    ]
