# Generated by Django 5.1.5 on 2025-01-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_infermiere_indirizzo_infermiere_reparto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infermiere',
            name='data_di_nascita',
            field=models.DateField(blank=True, default='1990/01/01', null=True),
        ),
        migrations.AlterField(
            model_name='segreteria',
            name='data_di_nascita',
            field=models.DateField(blank=True, default='1990/01/01', null=True),
        ),
    ]
