# Generated by Django 5.1.5 on 2025-01-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_infermiere_data_di_nascita_and_more'),
    ]

    operations = [
    ]
