# Generated by Django 5.1.5 on 2025-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_paziente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='referente_adulto',
            field=models.CharField(blank=True, help_text='Nome e cognome del referente adulto per i minori di 14 anni', max_length=100, null=True),
        ),
    ]
