# Generated by Django 5.1.5 on 2025-01-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_specializzazione'),
        ('users', '0007_remove_specializzazione'),
    ]

    operations = [
    ]
