# Generated by Django 5.1.5 on 2025-06-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_paziente_referente_adulto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestazioneInfermieristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('tipo', models.CharField(choices=[('prelievo', 'Prelievo'), ('medicazione', 'Medicazione')], max_length=20)),
                ('esito', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('infermiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.infermiere')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
            options={
                'verbose_name': 'Prestazione infermieristica',
                'verbose_name_plural': 'Prestazioni infermieristiche',
                'ordering': ['-data', '-ora'],
            },
        ),
    ]
