# Generated by Django 5.1.5 on 2025-05-12 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250130_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='infermiere',
            old_name='indirizzo',
            new_name='giorni_servizio',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='data_di_nascita',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='email',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='giorni_sala_medicazioni',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='giorni_sala_prelievi',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='password',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='reparto',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='infermiere',
            name='username',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_di_nascita',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='pazienti_convenzionati',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='specializzazione',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='username',
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='data_di_nascita',
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='username',
        ),
        migrations.RemoveField(
            model_name='segreteria',
            name='data_di_nascita',
        ),
        migrations.RemoveField(
            model_name='segreteria',
            name='password',
        ),
        migrations.RemoveField(
            model_name='segreteria',
            name='username',
        ),
        migrations.AddField(
            model_name='infermiere',
            name='codice_fiscale',
            field=models.CharField(default='DEFAULT_CF', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infermiere',
            name='id',
            field=models.BigAutoField(auto_created=True, default='DEFAULT_ID', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infermiere',
            name='user',
            field=models.OneToOneField(default='DEFAULT_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='assenze_pianificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='codice_fiscale',
            field=models.CharField(default='DEFAULT_CF', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='id',
            field=models.BigAutoField(auto_created=True, default='DEFAULT_ID', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='specialita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(default='NESSUN PAZIENTE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paziente',
            name='codice_fiscale',
            field=models.CharField(default='DEFAULT_ID', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paziente',
            name='data_nascita',
            field=models.DateField(default='INSERISCI DATA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paziente',
            name='id',
            field=models.BigAutoField(auto_created=True, default='DEFAULT', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paziente',
            name='luogo_nascita',
            field=models.CharField(default='DEFAULT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paziente',
            name='medico_curante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pazienti', to='users.medico'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='referente_adulto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paziente'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='user',
            field=models.OneToOneField(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segreteria',
            name='codice_fiscale',
            field=models.CharField(default='DEFAULT', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segreteria',
            name='id',
            field=models.BigAutoField(auto_created=True, default='DEFAULT', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segreteria',
            name='ruolo',
            field=models.CharField(default='Segreteria', max_length=100),
        ),
        migrations.AddField(
            model_name='segreteria',
            name='user',
            field=models.OneToOneField(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infermiere',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infermiere',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medici_sostituibili',
            field=models.ManyToManyField(blank=True, to='users.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='segreteria',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='segreteria',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('orario', models.TimeField()),
                ('tipo', models.CharField(choices=[('medico_curante', 'Visita con medico curante'), ('sostituto', 'Visita con medico sostituto'), ('urgenza', 'Visita d’urgenza')], max_length=20)),
                ('stato', models.CharField(default='Prenotato', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paziente')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('esito', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_users', to='users.medico')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_users', to='users.paziente')),
            ],
        ),
    ]
